### ISSUE TITLE
Image quality

### ISSUE THREAD

**Issue by daniel-gallo** [humansensinglab/ITI-GEN#3]
Hey,

First of all, congratulations for the paper, we found it extremely interesting. We were trying to replicate the results on our end, and came across some image quality issues. 

We trained the tokens as follows:
```shell
python train_iti_gen.py \
    --prompt='a headshot of a person' \
    --attr-list='Male,Skin_tone,Age' \
    --epochs=30 \
    --save-ckpt-per-epochs=10 \
    --device=0
```

Then, we generated the images by running
```shell
python generation.py \
    --config='models/sd/configs/stable-diffusion/v1-inference.yaml' \
    --ckpt='models/sd/models/ldm/stable-diffusion-v1/model.ckpt' \
    --plms \
    --attr-list='Male,Skin_tone,Age' \
    --outdir='./results/a_headshot_of_a_person_Male_Skin_tone_Age/' \
    --prompt-path='./ckpts/a_headshot_of_a_person_Male_Skin_tone_Age/original_prompt_embedding/basis_final_embed_19.pt' \
    --n_iter=5 \
    --n_rows=5 \
    --n_samples=1 \
    --gpu=0
```

We can see some samples below.
### Male + Skin tone 1 + Age 10-19
![grid_Male_positive_Skin_tone_1_Age_10_19](https://github.com/humansensinglab/ITI-GEN/assets/20315776/deb57540-c91d-4f40-9994-87bddb8f28d4)
### Male + Skin tone 3 + Age 3 - 9
![grid_Male_positive_Skin_tone_3_Age_3_9](https://github.com/humansensinglab/ITI-GEN/assets/20315776/c0eeef67-86e6-4b45-8570-736cce2f14b2)
### Woman + Skin tone 5 + Age 30 - 39
![grid_Male_negative_Skin_tone_5_Age_30_39](https://github.com/humansensinglab/ITI-GEN/assets/20315776/b6d5c191-5ecd-432a-af2e-ed7a21ae9d2a)

The images look alright, but we can notice there is "something off" around the eyes and nose. Thus, we were wondering if you modified any of the generator hyperparameters (scale, resolution, sampler, number of denoising steps...).

Thanks in advance, and congratulations again for the paper!

**Comment by czhang0528** [comment]
Thanks for your interest!

"If we modify any of the generator hyper-parameters (scale, resolution, sampler, number of de-noising steps…)?"
- No, we didn’t. The images we generated in the paper and the script in this codebase all follow the default setting of the official [SD codebase](https://github.com/CompVis/stable-diffusion).


"The images look alright, but we can notice there is "something off" around the eyes and nose."

- Regarding image quality, the bottleneck is the base generative model (SD v1-4 in our experiment), not ITI-GEN. ITI-GEN ensures the generated images contain desired attributes, not improving the image quality. Using advanced versions may improve the image quality such as SD 2-1 or SD-XL. Nevertheless, from Table 2 in the paper, we observe that by using reference images to guide the text embedding, the quality of the generated image is better than the vanilla SD v1-4.  

- Another factor might be the token length. For the combination of <age, gender, skin tone>, three tokens (i.e., 3 x 768) might not lead to optimal quality, mainly due to large combinations (i.e., 2 x 6 x 9 = 108 types). We use the same length (i.e., 3) in our paper mainly for a fair comparison and evaluation. Adjusting the token length and optimization time (e.g., different epochs) may help.

**Comment by daniel-gallo** [comment]
Thanks for the quick response! We'll try using some intermediate checkpoint instead of the last one (as you do in the README). 

Regarding the generator hyperparameters, we saw that in SD's [txt2img.py](https://github.com/CompVis/stable-diffusion/blob/main/scripts/txt2img.py), the scale is set to 7.5, while in ITI-GEN's [generation.py](https://github.com/humansensinglab/ITI-GEN/blob/main/generation.py) is set to 6. The default precision is also changed from "autocast" to "full", but I guess that doesn't hurt image quality.

**Comment by aditya10** [comment]
@czhang0528 Do you have any suggestions regarding adapting this code to SDXL? Seems like the codebases for SD v1 is quite simple compared to all other versions, so I am not sure if easy adaptation is possible at all. Any help will be welcome!
