### ISSUE TITLE
论文中的生成效果使用到的prompt模型（basis_final_embed_19.pt）后面开源吗

### ISSUE THREAD

**Issue by wanlipeng** [humansensinglab/ITI-GEN#6]
请问下，论文中的生成效果使用到的prompt模型（basis_final_embed_19.pt）后面开源吗，我们这边复现了下，改变年龄属性生成图质量很差，是和参考图的选择有关系吗？

**Comment by Xuanbai-Chen** [comment]
Thank you for your interest.

1. Whether will we make the model public?

The model, which is leveraged in the paper, was trained using the same script in this codebase and should not have too much difference compared with yours.

2. Poor image quality when changing age attribute.

Could you post some of the generated images here so that we can have more context? As a reminder, #3 proposes a similar question. In terms of the image quality, we emphasize the bottleneck is the base generative model, not ITI-GEN. ITI-GEN is just to make the generated image contain the desired attribute, not improving image quality.

3. Reference image selection.

As long as you utilize the images provided in this codebase, the performance should not differ a lot.

**Comment by wanlipeng** [comment]
Thanks for your reply, A very good job.
 I have got some good resultsby choose different learned embedding model.

**Comment by codermckee** [comment]
@wanlipeng 你好，请教下你生成的年龄图片，不同年龄段之间区分度高吗？以及生成的数据很符合对应的年龄段吗？  我实验了下好像不是很理想。

**Comment by Xuanbai-Chen** [comment]
@codermckee, Could you post some of your generated images here?
